name: Coding Standards

on:
  pull_request:
    branches:
      - main

jobs:
  coding-standards:
    if: github.event.pull_request.draft == false
    uses: alleyinteractive/.github/.github/workflows/php-coding-standards.yml@main
    with:
      php: '8.2'
